<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-08-19T14:39:36 IST" name="AuditSuite" finished-at="2025-08-19T14:40:13 IST" duration-ms="36337">
    <groups>
    </groups>
    <test started-at="2025-08-19T14:39:36 IST" name="DataDrivenTests" finished-at="2025-08-19T14:40:13 IST" duration-ms="36337">
      <class name="AuditCreate2.FullAuditFlowSplit1">
        <test-method is-config="true" signature="setup()[pri:0, instance:AuditCreate2.FullAuditFlowSplit1@547c04c4, instance params:[]]" started-at="2025-08-19T14:39:37 IST" name="setup" finished-at="2025-08-19T14:39:46 IST" duration-ms="8887" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="loginUser()[pri:1, instance:AuditCreate2.FullAuditFlowSplit1@547c04c4, instance params:[]]" started-at="2025-08-19T14:39:46 IST" name="loginUser" finished-at="2025-08-19T14:39:48 IST" duration-ms="2138" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginUser -->
        <test-method signature="goToDashboard()[pri:0, instance:AuditCreate2.FullAuditFlowSplit1@547c04c4, instance params:[]]" started-at="2025-08-19T14:39:48 IST" name="goToDashboard" finished-at="2025-08-19T14:39:49 IST" depends-on-methods="AuditCreate2.FullAuditFlowSplit1.loginUser" duration-ms="796" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- goToDashboard -->
        <test-method signature="createAudit()[pri:0, instance:AuditCreate2.FullAuditFlowSplit1@547c04c4, instance params:[]]" started-at="2025-08-19T14:39:49 IST" name="createAudit" finished-at="2025-08-19T14:40:13 IST" depends-on-methods="AuditCreate2.FullAuditFlowSplit1.goToDashboard" duration-ms="23711" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Audit creation failed or incorrect redirection. expected [http://localhost:5173/] but found [http://localhost:5173/schedule]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Audit creation failed or incorrect redirection. expected [http://localhost:5173/] but found [http://localhost:5173/schedule]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at AuditCreate2.FullAuditFlowSplit1.createAudit(FullAuditFlowSplit1.java:77)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createAudit -->
      </class> <!-- AuditCreate2.FullAuditFlowSplit1 -->
    </test> <!-- DataDrivenTests -->
  </suite> <!-- AuditSuite -->
</testng-results>
